name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install vsce
        run: sudo npm install -g vsce

      - name: Create the package
        run: ./pack.sh && mv *.vsix package.vsix

      - name: Publish
        run: vsce publish --packagePath package.vsix -p ${{ secrets.TOKEN }}

